import "./globals.css";

import { Header } from "@/layout";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html id="root-tag" lang="en">
      <body
        className={`bg-cc-ghost-white dark:bg-cc-eerie-black ${inter.className}`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
